---
- name: Ruby development headers
  apt: pkg=ruby1.9.1-dev state=present

- name: Install wpasupplicant
  apt: pkg=wpasupplicant state=present

- name: Install dnsmasq
  apt: pkg=dnsmasq state=present

- name: Don't start dnsmasq on boot
  service: name=dnsmasq enabled=no state=stopped

- name: Install hostapd
  apt: pkg=hostapd state=present

- name: Don't start hostapd on boot
  service: name=hostapd enabled=no state=stopped

- name: Install gem
  # TODO Install particular version of gem
  gem: name=wpa_cli_web state=present user_install=no
